version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gunicorn
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - PYTHONWARNINGS=ignore
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DEBUG=TRUE
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8081:8081"
    depends_on:
    - database
    command:
      bash -c "bash /tmp/scripts/wait-for-it.sh database:5432 --timeout=30 && /start.sh"
    volumes:
      - ./dockerfiles/scripts:/tmp/scripts

  app-uvicorn:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.uvicorn
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - WEB_CONCURRENCY=1
      - PYTHONWARNINGS=ignore
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DEBUG=TRUE
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8081:8081"
    depends_on:
    - database
    command:
      bash -c "bash /tmp/scripts/wait-for-it.sh database:5432 --timeout=30 && uvicorn tipg.main:app --host 0.0.0.0 --port 8081"
    volumes:
      - ./dockerfiles/scripts:/tmp/scripts

  database:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  # pg_featureserv:
  #   image: pramsey/pg_featureserv:latest
  #   environment:
  #     - DATABASE_URL=postgresql://username:password@database:5432/postgis
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #   - database

  # fast_features:
  #   image: ghcr.io/microsoft/ogc-api-fast-features:main
  #   environment:
  #     - APP_POSTGRESQL_PROFILE=stac_hybrid
  #     - APP_POSTGRESQL_HOST=database
  #     - APP_POSTGRESQL_PORT=5432
  #     - APP_POSTGRESQL_USER=username
  #     - APP_POSTGRESQL_PASSWORD=password
  #     - APP_POSTGERSQL_DBNAME=postgis
  #     - APP_DATA_SOURCE_TYPES=postgresql
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #   - database

  # pg_tileserv:
  #   image: pramsey/pg_tileserv:latest
  #   environment:
  #     - DATABASE_URL=postgresql://username:password@database:5432/postgis
  #   ports:
  #     - "7800:7800"
  #   depends_on:
  #   - database

  # martin:
  #   platform: linux/amd64
  #   image: maplibre/martin
  #   environment:
  #     - DATABASE_URL=postgresql://username:password@database:5432/postgis
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #   - database

  # t-rex:
  #   platform: linux/amd64
  #   image: sourcepole/t-rex
  #   ports:
  #     - "3000:3000"
  #   command:
  #     serve --dbconn postgresql://username:password@database:5432/postgis --bind=0.0.0.0 --port 3000
  #   depends_on:
  #     - database

